## Application config
app:
    superuser: 1
    maintenance: false
    functions:
        visits: false
        registration: false
    menu:
        user:
            left:
                - index
                - courses
                - quotes
        admin:
            left:
                - index
                - courses
                - quotes

### Database connections
connections:
    default:
        driver:
        host:
        database:
        username:
        password:

## Language config
lang:
    default_locale: it

mail:
    default_email:

## Debug
debug:
    enable: true
    enableWhoops: true
    whoopsEditor:
